In [2]:
# 导入Numpy包
import numpy
# 创建一个numpy数组
a = numpy.array([1,2,4,5,7,8])


In [3]:
# 输出数组查看
print(a)
# 查看a的类型
type(a)

[1 2 4 5 7 8]


numpy.ndarray

In [4]:
# 使用Numpy的内置函数shape查看数组的行数和列数
a.shape

(6,)

In [19]:
# 重新定义数组的行列（2,-1）代表2行，-1代表自适应，即数据值除以行数
print(a.reshape(2,-1))
print(a.shape)
# 此处会发现a.shape的值没有发生变化，原因是a.reshape(2，-1)不是直接改变a而是返回一个重新排列获得a,想要影响到原数组就需要如下操作
a=a.reshape(2,-1)
print(a.shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [12]:
# 重新排列a后想要对应位置输出可以不用像2维数组那样a[1][2]之类的输出结果
# 比如想输出5，可以如下,第一个参数为行号，第二个为列号，都是从零开始计算
print(a[1,0])

5


In [13]:
# 同理也可以进行赋值
a[1,0]=20
print(a)

[[ 1  2  4]
 [20  7  8]]


In [28]:
# 其他numpy的创建数组函数
# zeros创建初始元素全为0的矩阵，下面为创建3*2的矩阵，3行2列,值得注意的一点是，zeros的传入参数只有一个是一个元组(3,2)因此需要两个括号包围3,2
b = numpy.zeros((3,2))
print(b)
print()
# 同理，ones
c = numpy.ones((3,2))
print(c)
print()
# full函数，如下用法，第一个为元组，代表行列，第二个代表初始化元素
d = numpy.full((3,2),5)
print(d)
print()
# eye函数，创建单位矩阵，即左上角到右下角的那条对角线为1外其余都为0的n*n矩阵
e = numpy.eye(4)
print(e)
print()
# random.random函数，作用是创建一个矩阵，矩阵中每一个元素的数值都是随机的0-1之间的数
f = numpy.random.random((3,4))
print(f)
print()

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]

[[5 5]
 [5 5]
 [5 5]]

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

[[ 0.05572378  0.55175522  0.42465366  0.87221673]
 [ 0.67659518  0.15914015  0.36377084  0.19661748]
 [ 0.32019522  0.33655919  0.20262926  0.03259454]]

