In [2]:
# 创建样例数组
import numpy
a = numpy.array([1,2,3,4,5,6,7,8,9])
a = a.reshape(3,3)
print(a)
b = numpy.array([1,2,3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [6]:
# 需要进行让a每一行加上b
# 可以有的方法为
# 循环
for i in range(3):
    a[i,:] += b
print(a)
# 使用函数循环b
a = a + numpy.tile(b,(3,1))
print(a)
# 自带的广播，会让不同维度的数组进行调整成同纬度然后相加
print( a + b )

[[ 5 10 15]
 [ 8 13 18]
 [11 16 21]]
[[ 6 12 18]
 [ 9 15 21]
 [12 18 24]]
[[ 7 14 21]
 [10 17 24]
 [13 20 27]]
