In [6]:
import numpy
# 创建一个2*2和2*2的数组作为例子演示
a=numpy.array([1,2,3,4])
a=a.reshape([2,2])
b=numpy.array([9,10,11,12])
b=b.reshape([2,2])
print(a)
print(b)

[[1 2]
 [3 4]]
[[ 9 10]
 [11 12]]


In [18]:
# numpy中的数学运算和常用函数
# 数组相加相减相乘相除都是对应位置的数字进行对应操作的
c=a+b
print(c)
c=a-b
print(c)
c=a*b
print(c)
c=a/b
print(c)
# 这些在numpy中都有对应函数
c=numpy.add(a,b)
print(c)
c=numpy.subtract(a,b)
print(c)
c=numpy.multiply(a,b)
print(c)
c=numpy.divide(a,b)
print(c)
# 但是额外也有函数，如开方
print(numpy.sqrt(a))
# 矩阵相乘函数,前提条件是第一个参数列数等于第二个参数行数
print(numpy.dot(a,b))
print(a.dot(b))
# 求和函数
print(numpy.sum(a))
# 另外numpy可以单独对行或者对列进行操作，0就是对列，1就是对行
print(numpy.sum(a,axis=0))
print(numpy.sum(a,axis=1))
# mean函数求平均值，也具有axis参数，可以针对行列
print(numpy.mean(a))
# 随机数函数，下面是产生1-5之间的随机小数
print(numpy.random.uniform(1,5))
# 重复函数,第二个参数为元组，第一个值代表在列上重复的次数，第二个代表行上重复次数
print(numpy.tile(a,(2,3)))
# 排序函数，返回每一行的值的大小的排序,也具备axis属性，可以设置行列
print(a.argsort())
# 矩阵转置函数
print(a.T)
print(numpy.transpose(a))

[[10 12]
 [14 16]]
[[-8 -8]
 [-8 -8]]
[[ 9 20]
 [33 48]]
[[ 0.11111111  0.2       ]
 [ 0.27272727  0.33333333]]
[[10 12]
 [14 16]]
[[-8 -8]
 [-8 -8]]
[[ 9 20]
 [33 48]]
[[ 0.11111111  0.2       ]
 [ 0.27272727  0.33333333]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
[[31 34]
 [71 78]]
[[31 34]
 [71 78]]
10
[4 6]
[3 7]
2.5
4.740404629574038
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]
[[0 1]
 [0 1]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
