In [2]:
import numpy
# 创建一个3*4的数组作为例子演示
a=numpy.array([1,2,3,4,5,6,7,8,9,10,11,12])
a=a.reshape([3,4])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# 这样返回的是一个值，对应意思为，a的第二行，第三个数
print(a[1,2])
# 这样返回的是一个一维数组，对应参数意思为，a的第二行到最后一行，每个第二行的第三个数组成的一维数组
print(a[1:,2])
# 这样返回的是一个二维数组，意思是，a的第二行到最后一行，然后第二个参数到最后一个参数组成的二维数组
print(a[1:,2:])
# 要是是参数中含有-1指，从那个数组从后往前数
# 这个例子就是第一行从第一个元素到倒数第三个元素的一维数组【后一个参数最后的数字不会被概括】
print(a[0,0:-2])
# 这个例子是从第一行倒数第二个元素的到最后的一维数组
print(a[0,-2:])
# 可以采用arange()函数进行产生一个序列下是参数，0-2的一维数组,arange也可以有两个参数如arange(3,7)产生的就是3,4,5,6,
print(numpy.arange(3))
# 可以采用arange()对数组进行批量操作，如把数组每一行的的第二个参数值加一
a[numpy.arange(3),1]+=1
print(a)
# 数组索引的每一个值都可以是一个数组,如下意思是第1行的第2个元素和第三行的第3个元素等于5
a[[0,2],[1,2]]=5
print(a)
# 对于数组内元素判断大小有很方便的操作
result_a=a>10
print(result_a)
b=a[result_a]
print(b)

7
[7 5]
[[ 7  8]
 [ 5 12]]
[1 5]
[3 4]
[0 1 2]
[[ 1  6  3  4]
 [ 5 10  7  8]
 [ 9 14  5 12]]
[[ 1  5  3  4]
 [ 5 10  7  8]
 [ 9 14  5 12]]
[[False False False False]
 [False False False False]
 [False  True False  True]]
[14 12]
