In [2]:
import numpy as np
a = np.array([i for i in np.arange(10)])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.array([i for i in np.arange(29,39)])
b

array([29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [4]:
a = a.reshape(2,-1)
b = b.reshape(2,-1)

In [5]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
b

array([[29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38]])

In [9]:
x = np.concatenate([a,b])

In [10]:
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38]])

In [11]:
a[0,0]=213


In [12]:
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38]])

In [13]:
c = a[0:1,:3]
c

array([[213,   1,   2]])

In [15]:
c[0,1] = -1

In [16]:
c


array([[213,  -1,   2]])

In [17]:
a

array([[213,  -1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])